# -*- coding: utf-8 -*-
"""YOLOv5 Customobject detection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LCwqlA6F6cAt5lWKZH9tWSe8ebvRgG4g
"""

import os
from google.colab import drive
drive.mount('/content/drive')

os.chdir('/content/drive/My Drive/Custom Yolo') 
!ls

#!git clone https://github.com/ultralytics/yolov5  # clone repo
!pip install -U -r yolov5/requirements.txt  # install dependencies

#installing for google colab GPU use
!pip install torch==1.6.0+cu101 torchvision==0.7.0+cu101 -f https://download.pytorch.org/whl/torch_stable.html

# Commented out IPython magic to ensure Python compatibility.
# %cd yolov5

!ls

# Commented out IPython magic to ensure Python compatibility.

# %cat models/yolov5s.yaml

!python train.py --img 416 --batch 80 --epochs 50 --data './cust2.yaml' --cfg models/yolov5s.yaml

# Commented out IPython magic to ensure Python compatibility.
# Start tensorboard
# Launch after you have started training to all the graphs needed for inspection
# logs save in the folder "runs"
# %load_ext tensorboard
# %tensorboard --logdir /content/yolov5/runs/exp13





















